<?php

/**
 * Copyright (c) Andreas Heigl<andreas@heigl.org>
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 * @author    Andreas Heigl<andreas@heigl.org>
 * @copyright Andreas Heigl
 * @license   http://www.opensource.org/licenses/mit-license.php MIT-License
 * @since     19.09.2016
 * @link      http://github.com/heiglandreas/joindin-vm
 */
class TestApiMapper extends ApiMapper
{

    public function getDefaultFields()
    {
        return [
            'event_tz_place' => 'event_tz_place',
            'event_tz_cont' => 'event_tz_cont',
            'event_start_date' => 'event_start_date',
            'name' => 'name',
        ];
    }

    public function getVerboseFields()
    {
        return [];
    }

    public function buildLimit($resultsperpage, $start)
    {
        return parent::buildLimit($resultsperpage,
            $start); // TODO: Change the autogenerated stub
    }

    public function getPaginationLinks($list, $total = 0)
    {
        return parent::getPaginationLinks($list,
            $total); // TODO: Change the autogenerated stub
    }

    public function inflect($string)
    {
        return parent::inflect($string); // TODO: Change the autogenerated stub
    }
}
