/**
 * Issue #649 Switch database tables to InnoDB
 */

USE joindin;

ALTER TABLE `blog_cats` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `blog_comments` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `blog_post_cat` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `blog_posts` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `categories` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `countries` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `email_verification_tokens` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `event_comments` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `event_images` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `event_themes` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `event_track` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `events` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `invite_list` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `lang` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `meta_data` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `oauth_access_tokens` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `oauth_consumers` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `password_reset_tokens` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `patch_history` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `pending_talk_claims` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `reported_event_comments` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `reported_talk_comments` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `tags` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `tags_events` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `talk_cat` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `talk_comments` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `talk_link_types` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `talk_links` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `talk_speaker` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `talk_track` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `talks` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `twitter_request_tokens` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `user` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `user_admin` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `user_attend` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
ALTER TABLE `user_talk_star` ENGINE=InnoDB ROW_FORMAT=DYNAMIC;
