# https://dependabot.com/docs/config-file/

version: 1

update_configs:
  - package_manager: "php:composer"
    directory: "/"
    update_schedule: "live"
    version_requirement_updates: "increase_versions"
