<?php

namespace Joindin\Api\Test\Model;

use Joindin\Api\Model\ApiMapper;

final class TestApiMapper extends ApiMapper
{
    public function getDefaultFields(): array
    {
        return [
            'event_tz_place'   => 'event_tz_place',
            'event_tz_cont'    => 'event_tz_cont',
            'event_start_date' => 'event_start_date',
            'name'             => 'name',
        ];
    }

    public function getVerboseFields(): array
    {
        return [];
    }

    public function buildLimit(int $resultsperpage, int $start): string
    {
        return parent::buildLimit($resultsperpage, $start);
    }

    public function getPaginationLinks(array $list, int $total = 0): array
    {
        return parent::getPaginationLinks(
            $list,
            $total
        );
    }

    public function inflect(string $string): string
    {
        return parent::inflect($string); // TODO: Change the autogenerated stub
    }
}
